menu:
    Blog: /
    Archive: /archives/
    Weibo: http://weibo.com/3247395330
    GitHub: https://github.com/iostang
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus: iostang
duoshuo: iostang

# Analytics
# google-analytics:
ga: UA-65933410-1

# Copyright Infomation
startyear: 2015
